name = "my-cloud-hub"
compatibility_date = "2026-05-29"

[[d1_databases]]
binding = "DB"
database_name = "my-db"
database_id = "0b58d184-7a8d-4711-92a9-30d338a0b418"
migrations_dir = "../../packages/database/migrations"

[[kv_namespaces]]
binding = "WECHAT_KV"
id = "a95d6ea52307466e85bbb150aea487c6"

[[vectorize]]
binding = "VECTORIZE"
index_name = "todo-tasks"

[[durable_objects.bindings]]
name = "BLOCK_DUEL_ROOM"
class_name = "BlockDuelRoom"

[[migrations]]
tag = "v1_block_duel_room"
new_sqlite_classes = [ "BlockDuelRoom" ]
